# Basic Information
title: Jiahong Lyu
position: Undergraduate Student
affiliation: East China Normal University
email: kerwin19975906776@outlook.com

# Search Engine Optimization (SEO)
keywords: Jiahong Lyu, ECNU, Efficient AI, Linear Attention, Generative AI
description: Personal homepage of Jiahong Lyu, undergraduate at East China Normal University.
canonical: https://jiahonglyu.github.io/

# Links
google_scholar:
cv_link: assets/files/Jiahong_Lyu_CV.pdf
github_link: https://github.com/JiahongLyu
# linkedin: https://www.linkedin.com/
# twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon)
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# google_analytics:

# Use this project as a remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
